travis:
  secure:
    BINSTAR_TOKEN: OctaOxX6Pg4uNTjx76v+0rtSoV1J2M4K4eGPYRuFaqpU4EpH/AIGoNsFh4vHOp7NvL/pQdYsbTI87zmbuFJElt3ONUsb2A8x0eN/x/oF+7xxKBad0VXngQvU0DS4zIlBNOlrQjwV6R0hcFpmWXvQzf5CekTKPKF+BrU7w8swdCFwLR09jQwvTOYsy8K+cqnTdR5HPKMCK0I3WTPh0ERsgGocKDunXGr9OdJqIEMJmd4vZu/IYWmXX9KJ1bVhlVackFGfWhbGp6hFrWEWdCs6rl3a8szWdIzML2eErXxxGFV2nqmz0Z4Re+j6uqvKy0udz25De3VYgaiXSQsRwhE1/PecIMT1XG4YyQJGqDlwCuljFmegAK1OdKF5OxYiaRTL79EYU6tunyHHdanV8fzKmOc2M1ifR2yr6Y8mmNUoogCYlawU37XDsjdF1oIsz2TWbcjNs4wZDW3u+cpnX2+2mQ9ENr9jO2MSR4VjssOnl5pjaQJ4+ymoBElsPxfaMiMeR3g8LRUnsG8GVA8o0bsxuuqvHQr4qqQltLFcE4A6AD24+/8mVBayBmZp7CZoSj+T0Jf1iqI35UZvL8gOIw8MJ7cFYMeUHCU3NNoSWF10CC0zE17TnDlkJPjkV4fyqMj+Z7RzftY+FSyNLKcNVc9xAhcVy5BT1Mn3AtJsdR40GjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
